language: c
before_install:
- curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
- chmod 755 ./travis-tool.sh
- "./travis-tool.sh bootstrap"
install:
- "./travis-tool.sh install_deps"
- "./travis-tool.sh install_r microbenchmark knitr testthat"
- "./travis-tool.sh install_github jimhester/covr"
script: "./travis-tool.sh run_tests"
after_failure:
- "./travis-tool.sh dump_logs"
after_success:
- Rscript -e 'library(covr);coveralls()'
notifications:
  email:
    on_success: change
    on_failure: change
  hipchat:
    rooms:
      secure: JO0iWQXDAhK6TZxdNuiu7idLFAJjYBxxIMrGyWRz7GwB/el9D6Rp62orSGlgxCH9bbJPAczP6u7IRXr1+Z+bbktkMBnBvizomS3IohJQ1kSadWMjPz6IMfa18amOfIEYJWFn5Giq9hyl667JgBwGSM7+ZWAnnpJkE098D4Wc4mY=
    on_success: change
    on_failure: change
    template:
    - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}
      | Details: %{build_url} | Changes: %{compare_url}"
env:
- global:
  - WARNINGS_ARE_ERRORS=1
  - _R_CHECK_FORCE_SUGGESTS_=0
